Traceback (most recent call last):
  File "/home/gridsan/cguo/rep_e_icl/representation-engineering/repe_eval/tasks/csqa.py", line 65, in <module>
    dataset = csqa_dataset()
  File "/home/gridsan/cguo/rep_e_icl/representation-engineering/repe_eval/tasks/csqa.py", line 42, in csqa_dataset
    dataset = load_dataset("commonsense_qa")
  File "/home/gridsan/cguo/neuron-stats/stats/lib/python3.9/site-packages/datasets/load.py", line 1785, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/gridsan/cguo/neuron-stats/stats/lib/python3.9/site-packages/datasets/load.py", line 1514, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/gridsan/cguo/neuron-stats/stats/lib/python3.9/site-packages/datasets/load.py", line 1231, in dataset_module_factory
    raise e1 from None
  File "/home/gridsan/cguo/neuron-stats/stats/lib/python3.9/site-packages/datasets/load.py", line 1187, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type(e).__name__})")
ConnectionError: Couldn't reach 'commonsense_qa' on the Hub (ConnectionError)
